services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=verdantvibes
      - SCHEMA=backend
      - ANON=web_anon
      - AUTHENTICATOR=authenticator
    volumes:            
      - ./infra/postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - postgres_data:/var/lib/postgresql/data/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
volumes:
  postgres_data:
